In [1]:
import torch
import torch.nn as nn

# A single neuron: 3 inputs → 1 output
neuron = nn.Sequential(
    nn.Linear(3, 1),   # computes z = w·x + b
    nn.ReLU()          # applies f(z)
)

x = torch.tensor([[1.0, 2.0, 3.0]])
print(neuron(x))  # output after activation

tensor([[0.]], grad_fn=<ReluBackward0>)


In [2]:
# Dying ReLU
import torch
import torch.nn as nn
import torch.nn.functional as F

z = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

# Three equivalent ways
print(nn.ReLU()(z))           # as a layer
print(F.relu(z))              # as a function
print(torch.clamp(z, min=0))  # manual

# Output: tensor([0., 0., 0., 1., 2.])

tensor([0., 0., 0., 1., 2.])
tensor([0., 0., 0., 1., 2.])
tensor([0., 0., 0., 1., 2.])


In [3]:
# Sigmoid
z = torch.tensor([-3.0, 0.0, 3.0])

print(torch.sigmoid(z))
# tensor([0.0474, 0.5000, 0.9526])

# Use it as the last layer for binary classification:
model = nn.Sequential(
    nn.Linear(10, 1),
    nn.Sigmoid()       # output is now a probability
)

tensor([0.0474, 0.5000, 0.9526])


In [5]:
import torch
import torch.nn as nn

class SmallNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(784, 256)   # e.g. flattened 28x28 image
        self.fc2 = nn.Linear(256, 64)
        self.fc3 = nn.Linear(64, 10)     # 10 class scores

    def forward(self, x):
        x = F.gelu(self.fc1(x))   # hidden layers → GELU (or ReLU)
        x = F.gelu(self.fc2(x))
        x = self.fc3(x)           # final layer → NO activation here!
        return x                  # loss function (CrossEntropy) handles the rest

model = SmallNet()
x = torch.randn(32, 784)   # batch of 32 samples
out = model(x)
print(out.shape)            # torch.Size([32, 10])

torch.Size([32, 10])


In [6]:
import torch
import torch.nn as nn

# 3 inputs → 1 output score
neuron = nn.Linear(3, 1)

# Our ice cream inputs: [heat=9, mood=7, money=1]
inputs = torch.tensor([[9.0, 7.0, 1.0]])

score = neuron(inputs)
print(score)  # some number — the raw "should they buy?" score

tensor([[0.7541]], grad_fn=<AddmmBackward0>)


In [7]:
# FeedForward Network
import torch
import torch.nn as nn

# Build
model = nn.Sequential(
    nn.Linear(3, 8),
    nn.ReLU(),
    nn.Linear(8, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

# One person: [heat=9, mood=7, money=1]
person = torch.tensor([[9.0, 7.0, 1.0]])

# Forward pass — data flows through every layer left to right
output = model(person)
print(f"Probability of buying: {output.item():.0%}")

Probability of buying: 65%
